
package org.javacream.isbngenerator.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IsbnGeneratorWebService", targetNamespace = "http://services.javacream.org/store")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IsbnGeneratorWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerateNextIsbn")
    @WebResult(name = "GeneratedIsbn", targetNamespace = "")
    @RequestWrapper(localName = "GenerateNextIsbn", targetNamespace = "http://services.javacream.org/store", className = "org.javacream.isbngenerator.ws.client.GenerateNextIsbn")
    @ResponseWrapper(localName = "GenerateNextIsbnResponse", targetNamespace = "http://services.javacream.org/store", className = "org.javacream.isbngenerator.ws.client.GenerateNextIsbnResponse")
    @Action(input = "http://services.javacream.org/store/IsbnGeneratorWebService/GenerateNextIsbnRequest", output = "http://services.javacream.org/store/IsbnGeneratorWebService/GenerateNextIsbnResponse")
    public String generateNextIsbn();

}
