
package org.javacream.isbngenerator.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IsbnGeneratorWebServiceService", targetNamespace = "http://services.javacream.org/store", wsdlLocation = "http://localhost:9901/IsbnGeneratorWebService?wsdl")
public class IsbnGeneratorWebServiceService
    extends Service
{

    private final static URL ISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISBNGENERATORWEBSERVICESERVICE_EXCEPTION;
    private final static QName ISBNGENERATORWEBSERVICESERVICE_QNAME = new QName("http://services.javacream.org/store", "IsbnGeneratorWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9901/IsbnGeneratorWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION = url;
        ISBNGENERATORWEBSERVICESERVICE_EXCEPTION = e;
    }

    public IsbnGeneratorWebServiceService() {
        super(__getWsdlLocation(), ISBNGENERATORWEBSERVICESERVICE_QNAME);
    }

    public IsbnGeneratorWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISBNGENERATORWEBSERVICESERVICE_QNAME, features);
    }

    public IsbnGeneratorWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ISBNGENERATORWEBSERVICESERVICE_QNAME);
    }

    public IsbnGeneratorWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISBNGENERATORWEBSERVICESERVICE_QNAME, features);
    }

    public IsbnGeneratorWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsbnGeneratorWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IsbnGeneratorWebService
     */
    @WebEndpoint(name = "IsbnGeneratorWebServicePort")
    public IsbnGeneratorWebService getIsbnGeneratorWebServicePort() {
        return super.getPort(new QName("http://services.javacream.org/store", "IsbnGeneratorWebServicePort"), IsbnGeneratorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsbnGeneratorWebService
     */
    @WebEndpoint(name = "IsbnGeneratorWebServicePort")
    public IsbnGeneratorWebService getIsbnGeneratorWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.javacream.org/store", "IsbnGeneratorWebServicePort"), IsbnGeneratorWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISBNGENERATORWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ISBNGENERATORWEBSERVICESERVICE_EXCEPTION;
        }
        return ISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
