
package org.javacream.isbngenerator.fetch.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FetchingIsbnGeneratorWebService", targetNamespace = "http://ws.isbngenerator.javacream.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FetchingIsbnGeneratorWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GenerateNextIsbn")
    @WebResult(name = "GeneratedIsbns", targetNamespace = "")
    @RequestWrapper(localName = "GenerateNextIsbn", targetNamespace = "http://ws.isbngenerator.javacream.org/", className = "org.javacream.isbngenerator.fetch.ws.client.GenerateNextIsbn")
    @ResponseWrapper(localName = "GenerateNextIsbnResponse", targetNamespace = "http://ws.isbngenerator.javacream.org/", className = "org.javacream.isbngenerator.fetch.ws.client.GenerateNextIsbnResponse")
    @Action(input = "http://ws.isbngenerator.javacream.org/FetchingIsbnGeneratorWebService/GenerateNextIsbnRequest", output = "http://ws.isbngenerator.javacream.org/FetchingIsbnGeneratorWebService/GenerateNextIsbnResponse")
    public List<String> generateNextIsbn(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
