
package org.javacream.isbngenerator.fetch.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FetchingIsbnGeneratorWebServiceService", targetNamespace = "http://ws.isbngenerator.javacream.org/", wsdlLocation = "http://localhost:9902/FetchingIsbnGeneratorWebService?wsdl")
public class FetchingIsbnGeneratorWebServiceService
    extends Service
{

    private final static URL FETCHINGISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FETCHINGISBNGENERATORWEBSERVICESERVICE_EXCEPTION;
    private final static QName FETCHINGISBNGENERATORWEBSERVICESERVICE_QNAME = new QName("http://ws.isbngenerator.javacream.org/", "FetchingIsbnGeneratorWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9902/FetchingIsbnGeneratorWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FETCHINGISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION = url;
        FETCHINGISBNGENERATORWEBSERVICESERVICE_EXCEPTION = e;
    }

    public FetchingIsbnGeneratorWebServiceService() {
        super(__getWsdlLocation(), FETCHINGISBNGENERATORWEBSERVICESERVICE_QNAME);
    }

    public FetchingIsbnGeneratorWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FETCHINGISBNGENERATORWEBSERVICESERVICE_QNAME, features);
    }

    public FetchingIsbnGeneratorWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, FETCHINGISBNGENERATORWEBSERVICESERVICE_QNAME);
    }

    public FetchingIsbnGeneratorWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FETCHINGISBNGENERATORWEBSERVICESERVICE_QNAME, features);
    }

    public FetchingIsbnGeneratorWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FetchingIsbnGeneratorWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FetchingIsbnGeneratorWebService
     */
    @WebEndpoint(name = "FetchingIsbnGeneratorWebServicePort")
    public FetchingIsbnGeneratorWebService getFetchingIsbnGeneratorWebServicePort() {
        return super.getPort(new QName("http://ws.isbngenerator.javacream.org/", "FetchingIsbnGeneratorWebServicePort"), FetchingIsbnGeneratorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FetchingIsbnGeneratorWebService
     */
    @WebEndpoint(name = "FetchingIsbnGeneratorWebServicePort")
    public FetchingIsbnGeneratorWebService getFetchingIsbnGeneratorWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.isbngenerator.javacream.org/", "FetchingIsbnGeneratorWebServicePort"), FetchingIsbnGeneratorWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FETCHINGISBNGENERATORWEBSERVICESERVICE_EXCEPTION!= null) {
            throw FETCHINGISBNGENERATORWEBSERVICESERVICE_EXCEPTION;
        }
        return FETCHINGISBNGENERATORWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
